exp_name: llava_incomplete_im_caption_segframes_depthonly
device: 'gpu'
num_devices: 1
num_workers: 0

### loading checkpoints, eval, train options
num_epochs: 150
batch_size: 1
lr: 0.00001
weight_decay: 0.0001
lr_scheduler: "cosine"
eval_only: False # if this is set to True, only the val dataset will be run.
tune_lora: True
load_checkpoint: False

lora_model_path: False # /projectnb/ivc-ml/array/research/robotics/dreamworlds/checkpoints/llava_incomplete_im_caption_segframes_depth/glistening-springroll-2_60000

eval_every: 10000
num_eval_steps: 5
no_shuffle: False

train_dataset_choice: "ProcTHOR_image_caption"
train_dataset_args: {
  split: "train",
  model: "llava",
  model_path: liuhaotian/llava-v1.5-7b,
  use_seg_im: True,
  num_images: 1,
  use_depth_im: True,
  depth_alpha: 0.8,
}
train_collate_fn: "collate_fn"
 
## define your valtrain dataset, the name must match the class name in datasets/dataloaders.py. This is run during training to help choose best checkpoint
valtrain_dataset_choice:  "ProcTHOR_image_caption"
valtrain_dataset_args: {
  split: "valtrain",
  model: "llava",
  model_path: liuhaotian/llava-v1.5-7b,
  use_seg_im: True,
  num_images: 1,
  use_depth_im: True,
  depth_alpha: 0.8,
}

## define your val dataset, the name must match the class name in datasets/dataloaders.py. This is run only when eval_only is set to True
val_dataset_choice: "ProcTHOR_image_caption"
val_dataset_args: {
  split: "val",
  model: "llava",
  model_path: liuhaotian/llava-v1.5-7b,
  use_seg_im: True,
  num_images: 1,
  use_depth_im: True,
  depth_alpha: 0.8,
}
val_collate_fn: "collate_fn" 

#val_dataset_choice: "ADE20K"
#val_dataset_args: {
#  use_seg_im: True
#}
#val_collate_fn: "collate_fn" 

# The dataset __getitem__ must return a dictionary.


#define model. The name must match the class name in models/model_interface.py
model_choice: "LlavaModelInterface"
model_init_args: {
  temperature: 0,
  top_p: None,
  num_beams: 1,
  max_new_tokens: 768
}
# the model must output a huggingface output in its forward function.
 
# These are the inputs to the model. These variables must be present in the dictionary output from your dataloader in datasets/dataloaders.py.
model_input_choice: ['input_ids', 'attention_mask', 'pixel_values', 'labels']
 
# these are the losses. Must be defined in models/losses.py
# for each entry, the first variable is the loss name, the second entry is a list of argument inputs to the loss.
# The model outputs can be accessed by model_outputs[key]. The key is the ykey you defined in the dictionary output of the model forward
# The dataloader outputs (say the GT label) can be accessed similary in data_batch[] dictionary

losses: [] 
 
## Metrics [name, torchmetric_class_name_in_eval.py, metric init args, metric update args]:
metrics: [ 
#  ['HouseJsonSimilarity', 'HouseJsonSimilarity', [], []],
#  ['HouseSemanticSimilarity', 'HouseSemanticSimilarity', [], []]
]
